CREATE DATABASE IF NOT EXISTS steamproject;
USE steamproject;

CREATE TABLE IF NOT EXISTS User (
    SteamID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    UserName VARCHAR(100) UNIQUE NOT NULL,
    Phone INT UNIQUE,
    Email VARCHAR(100) UNIQUE NOT NULL,
    UserPassword VARCHAR(100) NOT NULL,
    Country VARCHAR(50),
    CreationDate DATE NOT NULL,
    UserStatus VARCHAR(50) NOT NULL DEFAULT 'Disconnected'
);

CREATE TABLE IF NOT EXISTS Friends (
    UserID INT NOT NULL,
    UserFriendID INT NOT NULL,
    PRIMARY KEY (UserID, UserFriendID),
    FOREIGN KEY (UserID) REFERENCES User(SteamID) ON DELETE CASCADE,
    FOREIGN KEY (UserFriendID) REFERENCES User(SteamID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Genre (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Game (
    Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    GameName VARCHAR(50) NOT NULL,
    GenreID INT NOT NULL,
    Developer VARCHAR(50) NOT NULL,
    ReleaseDate DATE NOT NULL,
    Cost INT NOT NULL DEFAULT 0,
    FOREIGN KEY (GenreID) REFERENCES Genre(ID)
);

CREATE TABLE IF NOT EXISTS SteamLibrary (
    UserID INT NOT NULL,
    GameID INT NOT NULL,
    PRIMARY KEY (UserID, GameID),
    FOREIGN KEY (UserID) REFERENCES User(SteamID) ON DELETE CASCADE,
    FOREIGN KEY (GameID) REFERENCES Game(Id) ON DELETE CASCADE
);

INSERT INTO Genre (Nombre) VALUES ('Action');

INSERT INTO Genre (Nombre) VALUES ('Adventure');

INSERT INTO Genre (Nombre) VALUES ('Casual');

INSERT INTO Genre (Nombre) VALUES ('Indie');

INSERT INTO Genre (Nombre) VALUES ('Multiplayer');

INSERT INTO Genre (Nombre) VALUES ('Racing');

INSERT INTO Genre (Nombre) VALUES ('RPG');

