
CREATE TABLE IF NOT EXISTS User (
    SteamID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    UserName VARCHAR(100) UNIQUE NOT NULL,
    Phone INT UNIQUE,
    Email VARCHAR(100) UNIQUE NOT NULL,
    UserPassword VARCHAR(100) NOT NULL,
    Country VARCHAR(50),
    CreationDate DATE NOT NULL,
    UserStatus VARCHAR(50) NOT NULL DEFAULT 'Disconnected'
);

CREATE TABLE IF NOT EXISTS Friends (
    UserID INT NOT NULL,
    UserFriendID INT NOT NULL,
    PRIMARY KEY (UserID, UserFriendID),
    FOREIGN KEY (UserID) REFERENCES User(SteamID) ON DELETE CASCADE,
    FOREIGN KEY (UserFriendID) REFERENCES User(SteamID) ON DELETE CASCADE
);

-- Create Genre and Dev tables first
CREATE TABLE IF NOT EXISTS Genre (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Dev (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DevName VARCHAR(50) UNIQUE NOT NULL,
    DevInfo VARCHAR(255) NOT NULL
);

-- Now create Game, since Genre and Dev exist
CREATE TABLE IF NOT EXISTS Game (
    Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    GameName VARCHAR(50) UNIQUE NOT NULL,
    GenreID INT NOT NULL,
    DevID INT NOT NULL,
    ReleaseDate DATE NOT NULL,
    Cost INT NOT NULL DEFAULT 0,
    FOREIGN KEY (GenreID) REFERENCES Genre(ID),
    FOREIGN KEY (DevID) REFERENCES Dev(ID) 
);

CREATE TABLE IF NOT EXISTS SteamLibrary (
    UserID INT NOT NULL,
    GameID INT NOT NULL,
    PRIMARY KEY (UserID, GameID),
    FOREIGN KEY (UserID) REFERENCES User(SteamID) ON DELETE CASCADE,
    FOREIGN KEY (GameID) REFERENCES Game(Id) ON DELETE CASCADE
);

